name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Roda à meia-noite todos os dias
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configurações Gerais
          user: Gladistony
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Plugin Languages (focado em Starred e afinidade)
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          
          # Plugin WakaTime (Tempo de codificação)
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: languages, editors, os
          
          # Ajuste de Layout
          config_timezone: America/Recife
