name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Gladistony
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Recife
          
          # PLUGIN LANGUAGES: Otimizado para evitar timeout
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_indepth: no          # Mudamos para 'no' para evitar o aviso amarelo
          plugin_languages_analysis_timeout: 15 # Aumenta o tempo limite de an√°lise
          plugin_languages_categories: markup, programming
          plugin_languages_ignored: html, css, tex, roff, journal, text
          
          # PLUGIN STARLISTS
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 5

          # PLUGIN WAKATIME
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 14
          plugin_wakatime_sections: languages, editors, os
